// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  block__row: string;
  'block__content': string;
  'block__element': string;
  'block__element_2': string;
  'block__element_4': string;
  'block__row': string;
}
export const cssExports: CssExports;
export default cssExports;
